// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eygedvepmuwllwcefimq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5Z2VkdmVwbXV3bGx3Y2VmaW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTk5NjIsImV4cCI6MjA1ODI5NTk2Mn0.RZ2-hipNcemzQALtTzyJ8oVujza9Ua5s1-0Q8yaoKpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);